; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B2F7DD81-D037-4F68-87B9-573AC4D73017}
AppName=Interface Agreg
AppVersion=$version
AppPublisher=Ecole Normale Superieure
DefaultDirName={pf}\Interface Agreg
DisableProgramGroupPage=yes
OutputDir=C:\noms\pierre\tmp\tmp_build\tpmontrouge\scripts\dist
OutputBaseFilename=interface_agreg_setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\noms\pierre\tmp\tmp_build\tpmontrouge\scripts\dist\interface_gui\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Interface Agreg"; Filename: "{app}\interface_gui.exe"
Name: "{commondesktop}\Interface Agreg"; Filename: "{app}\interface_gui.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\interface_gui.exe"; Description: "{cm:LaunchProgram,Interface Agreg}"; Flags: nowait postinstall skipifsilent

